### ISSUE TITLE
Push method in FeedClient doesn't delete temporary zip or xml files after throwing errors.

### ISSUE THREAD

**Issue by RasPat1** [unbxd/java-sdk#3]
Hey Guys,

We're using unbxd sdk 2.1 for a high load web app. We've traced down a bug causing our server's disks to fill up to the code in unbxd sdk.  It seems the code is not deleting the temporary files it creates after pushing to unbxd.  We've ended up with a temp folder filled with unbxd xml and zip files causing our a server to hang.  Please let me know if this is fixed in a newer version or when it will be fixed.
I'm available for more details.  Please let me know.

Thanks,
Ras

**Comment by gowda** [comment]
Fixed by #4
